name: studyRecord
on:
    push:
      branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "22"

            - name: Install dependencies
              run: npm install

            - name: Check environment variables
              run: |
                echo "Checking environment variables..."
                echo "VITE_SUPABASE_URL is set: $([[ -n "$VITE_SUPABASE_URL" ]] && echo 'YES' || echo 'NO')"
                echo "VITE_SUPABASE_ANON_KEY is set: $([[ -n "$VITE_SUPABASE_ANON_KEY" ]] && echo 'YES' || echo 'NO')"
                echo "VITE_SUPABASE_URL length: ${#VITE_SUPABASE_URL}"
                echo "VITE_SUPABASE_ANON_KEY length: ${#VITE_SUPABASE_ANON_KEY}"
              env:
                VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
                VITE_SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}

            - name: Run build
              run: npm run build
              env:
                VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
                VITE_SUPABASE_ANON_KEY: ${{secrets.VITE_SUPABASE_ANON_KEY}}
              
              ##ビルドでできた dist フォルダをデプロイで使えるように保存
            - name: Upload build-artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build-artifacts
                path: dist
            
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "22"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test        
    
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "22"

            - name: Install dependencies
              run: npm install
        
              ## ビルドジョブで生成＆保存されたdistフォルダを取得
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                name: build-artifacts
                path: dist

            - name: Install firebase-tools
              run: npm install --save-dev firebase-tools

            - name: Decode Firebase service account key
              run: |
                echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
                echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV
            
            - name: change space
              run: ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}

            - name: Deploy to Firebase Hosting
              run: |
                ./node_modules/.bin/firebase deploy
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                FIREBASE_CLI_EXPERIMENTS: webframeworks

            - name: delete GOOGLE_APPLICATION_CREDENTIALS
              run: rm $GOOGLE_APPLICATION_CREDENTIALS
              if: ${{ always() }}


